### ISSUE TITLE
Adapt to the v1.6.10?

### ISSUE THREAD

**Issue by IamComing3** [wenxuanjun/laravel-adminlte3#1]
v1.6.10 adds a lot of things, such as list modal etc. Is this set compatible?

**Comment by wenxuanjun** [comment]
It seems OK.

**Comment by wenxuanjun** [comment]
I'am sorry.There is something error.I will fix it soon.

**Comment by wenxuanjun** [comment]
It works properly now.

But because the Modal Class is a bit of hassle to modify by extension (it will take me a period of time), the Modal may have some display problems.I may repair it in the future.
