### ISSUE TITLE
View [grid.fixed-table] not found.

### ISSUE THREAD

**Issue by sdjtu502** [wenxuanjun/laravel-adminlte3#10]
`
    /**
     * Find the given view in the list of paths.
     *
     * @param  string  $name
     * @param  array   $paths
     * @return string
     *
     * @throws \InvalidArgumentException
     */
    protected function findInPaths($name, $paths)
    {
        foreach ((array) $paths as $path) {
            foreach ($this->getPossibleViewFiles($name) as $file) {
                if ($this->files->exists($viewPath = $path.'/'.$file)) {
                    return $viewPath;
                }
            }
        }
 
        throw new InvalidArgumentException("View [$name] not found.");
    }
 
    /**
     * Get an array of possible view files.
     *
     * @param  string  $name
     * @return array
     */
    protected function getPossibleViewFiles($name)
    {
        return array_map(function ($extension) use ($name) {
            return str_replace('.', '/', $name).'.'.$extension;
        }, $this->extensions);
    }
 
    /**
     * Add a location to the finder.
     *
     * @param  string  $location
     * @return void
Arguments
"View [grid.fixed-table] not found."
`

**Comment by wonbin2011** [comment]
blade 视图文件覆盖不全 垃圾扩展没法用
