### ISSUE TITLE
好像缺少 wenxuanjun/laravel-adminlte3/dist/css/app.css 和 wenxuanjun/laravel-adminlte3/dist/img/AdminLTELogo.png 文件

### ISSUE THREAD

**Issue by wxMai** [wenxuanjun/laravel-adminlte3#6]
我的 laravel-admin 版本是1.7
安装了 laravel-adminlte3 后样式错乱了。
好像是由于缺少 wenxuanjun/laravel-adminlte3/dist/css/app.css 文件的原因？
另外 wenxuanjun/laravel-adminlte3/dist/img/AdminLTELogo.png 这个文件也是缺失的。

**Comment by wenxuanjun** [comment]
Thanks for your issue.

I'm sure it will be fixed soon.

**Comment by wenxuanjun** [comment]
There is no problem now.
