### ISSUE TITLE
editable 样式错乱

### ISSUE THREAD

**Issue by KeepXin** [wenxuanjun/laravel-adminlte3#8]
您好，(editable 样式错乱)这个问题修复了吗

**Comment by yangzi1028** [comment]
可以将bootstrap-editable.min.js更新到1.5.3版本

**Comment by yangzi1028** [comment]
现在有个新的问题，点击 editable 元素的时候，会自动滚动到页面顶部，而且其他的 a 标签也会出现这样的情况

**Comment by wenxuanjun** [comment]
最近会尝试把所有的plugins更新
