### ISSUE TITLE
文件缺失？

### ISSUE THREAD

**Issue by Chenjiajing** [wenxuanjun/laravel-adminlte3#9]
InvalidArgumentException In FileViewFinder.php line 137 :
View [grid.dropdown-actions] not found.

使用场景: 点击侧栏自带的角色管理(Admin/Role)，直接提示
 InvalidArgumentException In FileViewFinder.php line 137 :
View [grid.dropdown-actions] not found.
是文件缺失还是我的配置问题？
环境:  laravel 5.7,laravel-admin:1.73

**Comment by wenxuanjun** [comment]
可能是您的问题，更新到laravel 5.8试试？
